name = "stefanuk12/example_project"
description = "An opinionated project layout for Roblox exploit scripts."
version = "0.1.0"
authors = ["Stefanuk12"]
license = "MIT"
includes = ["pesde.toml", "README.md", "LICENSE", "src/*"]

[engines]
pesde = "^0.7.1"

[target]
build_files = ["src"]
environment = "roblox"
# Remove bin AND lib, if you are not publishing to the registry
bin = "src/main.luau" # Remove this, if this is not a binary
lib = "src/init.luau" # Remove this, if this is not a library

[scripts]
roblox_sync_config_generator = ".pesde/scripts/roblox_sync_config_generator.luau"
sourcemap_generator = ".pesde/scripts/sourcemap_generator.luau"

[indices]
default = "https://github.com/pesde-pkg/index"

[wally_indices]
default = "https://github.com/UpliftGames/wally-index"

[dependencies]
# Example dependency below, remove it if you don't need it
promise = { wally = "evaera/promise", version = "^4.0.0" }

[dev_dependencies]
luau_defs = { repo = "rocult/luau-defs", rev = "e628aec6fabb5acfd28f1bc6a18a1c7950122d2c", target = "luau" }
scripts = { name = "pesde/scripts_rojo", version = "^0.2.0", target = "lune" }
